### PR TITLE
Upgrading Parinfer dependency to version 2.5.2 and removing npm node_modules from repo

### PR DESCRIPTION
**Pull request by rgdelato**
Upgrading to the latest version of Parinfer, and also removing the `node_modules` directory from the repo, since the npm dependencies should be installed on the user's machine when Atom installs a package.

### CODE REVIEW

**Comment by shaunlebron** [comment]
Just a heads up—@oakmac currently prefers v1 over v2, due to a disagreement over how to handle [edge case #1 described here](https://www.youtube.com/watch?v=CiDtmPKVskk). You can try the edge case in [demo-v1] and [demo-v2].

To clarify, this is only a disagreement over edge-case behavior.  90% of the time they behave completely the same.  But 10% of the time, v1 will misplace parens to maintain balance, whereas v2 will pause, highlight the problem, and resume when fixed.

[demo-v1]:http://shaunlebron.github.io/parinfer/demo-v1
[demo-v2]:http://shaunlebron.github.io/parinfer/demo

parinferv1v2v3

The v1 path in red above is longer because you need to manually fix misplaced parens (if you even notice them).  v2 takes a shorter path in blue, allowing and highlighting a mismatched paren rather than misplacing it.

Both require manual fixes, but my choice for v2 is based on minimizing surprise, because "always-balanced" doesn't mean much if we are misplacing parens to achieve it.

v3 is ideal behavior that requires a new change-based inference which I'm starting here: https://github.com/shaunlebron/parinfer/issues/138

**Comment by oakmac** [comment]
Shaun is correct: I consider Parinfer v2 to be an unacceptable regression of behavior for Parinfer. We have discussed this some, but not at great length.

IMO, Indent Mode's guarantee of "always balanced parens" is not worth sacrificing for a few edge cases where the intended AST result may be ambiguous. I think the current behavior of v1 in the example from the video above is fine. It also prevents very bad situations like the following:

parinfer-v2-trouble

Consider what would happen if a user pasted some code during the "temporary imbalanced" state.

From the README of this project:

> Put simply: the goal of Parinfer is to make it so you never have to think about "balancing your parens" when writing or editing Lisp code.

Parinfer has never made guarantees about "understanding your code". It has always been about inferring structure based on indentation with a guarantee of a balanced AST without hotkeys. Parinfer v2 violates that guarantee.

**Comment by shaunlebron** [comment]
Parinfer may have taken a life of its own, as ideas often do, but for what it's worth—your basic premise about the "goal"  or "guarantee of balance" in Parinfer is not anywhere in the canonical literature on Parinfer (old or new).

Always-balanced was what I thought was a nice side effect of some of the rules I made for making parens _easier_ to balance.  I retracted that side effect in v2 because it felt like a false promise. And I always found paredit a bit of a straitjacket in forcing balance all the time.  I don't think it's unreasonable to see Parinfer v2 as a compromise in the center of that spectrum—between always manually-balanced and always auto-balanced.

About your new edge-case: I think it's good to know that a user could accidentally paste a long paren trail like that, but I really doubt their instinct for fixing it would be to _add more parens_ inside it. So I wouldn't rank it as more severe than the edge-case in the video, since it is based on what I've actually seen while coding. A user told me they silently stopped using Parinfer because of it, since I imagine it's hard to report a detailed bug about something that happens under your nose.  So it's hard to assume in this case that no bug reports means no complaints.

All this to say, what can we do to avoid a fork?

1. add an option?
1. wait for an ideal v3?

**Comment by oakmac** [comment]
It is irrelevant whether "guarantee of balance" was intended or not, or documented or not. It is a current behavior of this plugin that will be significantly changed by adopting Parinfer v2. Like I mentioned before, I consider this change a regression to the user experience.

The best thing about Parinfer is that it requires practically no learning curve. There are only two things a user really needs to understand in order to use Parinfer:

1) The relationship between indentation and structure.
2) Paren Mode will run on their file the first time they open it.

Even these two rules<sup>1</sup> can be a source of confusion for new users judging by Issues that have been opened against this repo.

This change adds a new rule<sup>2</sup> and also requires **specific user behavior** when that rule is triggered. The state diagram image above is inaccurate because it assumes that the user correctly goes from the white dot to the balanced dark dot. It does not show that you can go from an unbalanced white dot to another unbalanced white dot to another unbalanced white dot, etc. Parinfer v1 has no white dots; only balanced dark ones.

> All this to say, what can we do to avoid a fork? Add an option? Wait for an ideal v3?

I support waiting for a v3. I suppose a practical thing to do is offer this behavior behind a config flag for users who really want it.

<sup>1</sup> I am aware there has always been the documented edge case around balanced quote characters. To date, no one has mentioned having any problems with this. I suspect this is because practically every programming language in existence has similar contraints for string literals.

<sup>2</sup> It adds two rules if you count the leading-closing-paren change.

**Comment by shaunlebron** [comment]
you're willing to add v2 behind a config flag while we wait for v3?

**Comment by shaunlebron** [comment]
2.5.0 adds `forceBalance` option to restore v1's aggressive balancing behavior (defaults to false)

[try it here](http://shaunlebron.github.io/parinfer/demo)

(this restores v1 behavior for _both_ edge cases detailed in the video, allowing atom-parinfer to take advantage of other fixes/enhancements in v2)

**Comment by rgdelato** [comment]
@oakmac I've upgraded the pull request to Parinfer v2.5.0 and added a "force-balance?" config option that defaults to "true"

**Comment by rgdelato** [comment]
Closing this PR since work is already being done to upgrade to Parinfer v3.

**Pull request closed without merging**
